add description to readme
interactive rebase in progress; onto b2a6aeb
Last command done (1 command done):
   pick d17b190 add description to readme
No commands remaining.
You are currently rebasing branch 'main' on 'b2a6aeb'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   AndjelaKostic5119
        new file:   README.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   AndjelaKostic5119 (untracked content)

PS C:\Users\akostic\shop-asp-project> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD main
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
PS C:\Users\akostic\shop-asp-project> git push origin main
To github.com:andjela-kostic/shop-asp-project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\akostic\shop-asp-project> git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD:main
Everything up-to-datePS C:\Users\akostic\shop-asp-project> git status
interactive rebase in progress; onto b2a6aeb
Last command done (1 command done):
   pick d17b190 add description to readme
No commands remaining.
You are currently rebasing branch 'main' on 'b2a6aeb'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   AndjelaKostic5119
        new file:   README.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   AndjelaKostic5119 (untracked content)

PS C:\Users\akostic\shop-asp-project> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD main
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
PS C:\Users\akostic\shop-asp-project> git push origin main
To github.com:andjela-kostic/shop-asp-project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\akostic\shop-asp-project> git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD:main
Everything up-to-datet)
PS C:\Users\akostic\shop-asp-project> git status
interactive rebase in progress; onto b2a6aeb
Last command done (1 command done):
   pick d17b190 add description to readme
No commands remaining.
You are currently rebasing branch 'main' on 'b2a6aeb'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   AndjelaKostic5119
        new file:   README.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   AndjelaKostic5119 (untracked content)

PS C:\Users\akostic\shop-asp-project> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD main
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
PS C:\Users\akostic\shop-asp-project> git push origin main
To github.com:andjela-kostic/shop-asp-project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\akostic\shop-asp-project> git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD:main
Everything up-to-datePS C:\Users\akostic\shop-asp-project> git status
interactive rebase in progress; onto b2a6aeb
Last command done (1 command done):
   pick d17b190 add description to readme
No commands remaining.
You are currently rebasing branch 'main' on 'b2a6aeb'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   AndjelaKostic5119
        new file:   README.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   AndjelaKostic5119 (untracked content)

PS C:\Users\akostic\shop-asp-project> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD main
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
PS C:\Users\akostic\shop-asp-project> git push origin main
To github.com:andjela-kostic/shop-asp-project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\akostic\shop-asp-project> git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD:main
Everything up-to-datePS C:\Users\akostic\shop-asp-project> git status
interactive rebase in progress; onto b2a6aeb
Last command done (1 command done):
   pick d17b190 add description to readme
No commands remaining.
You are currently rebasing branch 'main' on 'b2a6aeb'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   AndjelaKostic5119
        new file:   README.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   AndjelaKostic5119 (untracked content)

PS C:\Users\akostic\shop-asp-project> git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD main
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
PS C:\Users\akostic\shop-asp-project> git push origin main
To github.com:andjela-kostic/shop-asp-project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:andjela-kostic/shop-asp-project.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\akostic\shop-asp-project> git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

PS C:\Users\akostic\shop-asp-project> git push origin HEAD:main
Everything up-to-date#